### ISSUE TITLE
v0.6.0: `Clojure.eval("(+ 1 2)")` does not work

### ISSUE THREAD

**Issue by alexander-myltsev** [mikera/clojure-utils#1]
`Clojure.eval("(+ 1 2)")` does not work. May be because of Scala. You may try it at [my simple project](https://github.com/alexander-myltsev/riemann-runner).

v0.4.0 works fine.

Good luck with fixing!

**Comment by alexander-myltsev** [comment]
Better to look at [this commit](https://github.com/alexander-myltsev/riemann-runner/commit/c71179db1e8055bc8d4d867d4449b2b1e71c3824).

**Comment by mikera** [comment]
It works for me - what error are you getting?

**Comment by alexander-myltsev** [comment]
Hm. Weird. Works fine now. Issue is closed.
